[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
framework = arduino
board = seeed_xiao_esp32c6


; 4MB Flash, no SPIFFS needed
board_build.partitions = min_spiffs.csv
board_build.flash_mode = dio

lib_deps = 
    h2zero/NimBLE-Arduino@^2.5.0
    bblanchon/ArduinoJson@^6.21.2
    https://github.com/ivanseidel/LinkedList.git

build_flags = 
    -DMARAUDER_TUI
    -DCORE_DEBUG_LEVEL=0
    -w
    -Wl,-zmuldefs

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = min_spiffs.csv
board_build.flash_mode = dio
lib_deps = 
    h2zero/NimBLE-Arduino@^2.5.0
    bblanchon/ArduinoJson@^6.21.2
    https://github.com/ivanseidel/LinkedList.git
build_flags = 
    -DMARAUDER_TUI
    -DCORE_DEBUG_LEVEL=0
    -w
    -Wl,-zmuldefs
